pipeline {
  agent any

  stages {
    stage('Printing Hello World') {
      steps {
        echo "Printing echo from 'jfr-poc-repo-fork/jenkinsfile-runner-prepackaged/test' path"
      }
    }
  }
}
